import { execSync } from "child_process";
import { generateCryptoFile } from "./creator.js";
import OpenAI from "openai";
import "dotenv/config";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const COMMITS = parseInt(process.env.COMMITS_PER_DAY) || 20;
const PROJECT_STYLE = process.env.PROJECT_STYLE || "defi";

async function generateCommitMessage(summary, projectStyle) {
  const prompt = `
You are generating a concise, realistic git commit message for a ${projectStyle} blockchain project.
Do NOT use the words "autogenerated" or "generated".
Use conventional commit style.
Describe the change naturally in 1 line.

File summary: ${summary}
`;
  const response = await openai.chat.completions.create({
    model: "gpt-4.1-mini",
    messages: [{ role: "user", content: prompt }],
    max_tokens: 20,
    temperature: 0.4
  });
  return response.choices[0].message.content.trim();
}

async function main() {
  for (let i = 1; i <= COMMITS; i++) {
    const { filePath, type, content } = await generateCryptoFile();

    // Prepare a summary for commit
    const summary = `${type} generated: ${filePath}`;

    // Generate realistic commit message
    const commitMsg = await generateCommitMessage(summary, PROJECT_STYLE);

    // Stage and commit
    execSync(`git add "${filePath}"`);
    execSync(`git commit -m "${commitMsg}"`);

    console.log(`✔ Commit ${i}/${COMMITS}: ${commitMsg}`);
  }

  execSync(`git push origin ${process.env.GIT_BRANCH}`);
  console.log("✅ All commits pushed");
}

main().catch(console.error);
